apiVersion: v1
kind: Service
metadata:
  name: {{ include "yarp-k8s-ingress-controller.fullname" . }}
  labels:
    {{- include "yarp-k8s-ingress-controller.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - name: proxy
      port: 80
      protocol: TCP
      targetPort: 8000
    - name: proxy-ssl
      port: 443
      protocol: TCP
      targetPort: 8443
  selector:
    {{- include "yarp-k8s-ingress-controller.selectorLabels" . | nindent 4 }}
